name: Deploy on GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: yarn install
      run: yarn --frozen-lockfile
    - name: yarn build
      run: yarn build
      env:
        NODE_ENV: 'production'
        SITE_ROOT: 'https://aragon.one/'
    - name: push to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        cname: 'aragon.one'
        deploy_key: ${{ secrets.GH_PAGES_ACTIONS_DEPLOY_KEY }}
        publish_dir: ./dist
