name: Deploy on GitHub Pages

on: push

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: yarn install
      run: yarn --frozen-lockfile
    - name: yarn build
      run: yarn build
      env:
        NODE_ENV: 'production'
        SITE_ROOT: 'https://aragon.org/'
